package com.example.repository;

import com.example.dto.WalletTransactionDTO;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertAll;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

@JdbcTest
@Import(WalletTransactionRepository.class)
@TestPropertySource(properties = "spring.sql.init.mode=never")
class WalletTransactionRepositoryTest {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private WalletTransactionRepository repository;

    // ── Schema Setup ─────────────────────────────────────────────────────────────

    @BeforeEach
    void setUpSchema() {
        jdbcTemplate.execute("DROP ALL OBJECTS");
        // No FK to users so tests stay self-contained
        jdbcTemplate.execute("""
                CREATE TABLE wallet_transactions (
                    transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id        BIGINT NOT NULL,
                    transaction_type VARCHAR(50) NOT NULL,
                    amount         DECIMAL(19, 2) NOT NULL,
                    balance_before DECIMAL(19, 2) NOT NULL,
                    balance_after  DECIMAL(19, 2) NOT NULL,
                    created_at     TIMESTAMP
                )
                """);
    }

    // ── save ─────────────────────────────────────────────────────────────────────

    @Test
    void save_returnsDto_withGeneratedIdAndAllFields() {
        WalletTransactionDTO result = repository.save(
                1L, "DEPOSIT",
                new BigDecimal("500.00"),
                new BigDecimal("1000.00"),
                new BigDecimal("1500.00")
        );

        assertAll(
                () -> assertNotNull(result.transactionId()),
                () -> assertEquals(1L,                          result.userId()),
                () -> assertEquals("DEPOSIT",                   result.transactionType()),
                () -> assertEquals(new BigDecimal("500.00"),    result.amount()),
                () -> assertEquals(new BigDecimal("1000.00"),   result.balanceBefore()),
                () -> assertEquals(new BigDecimal("1500.00"),   result.balanceAfter()),
                () -> assertNotNull(result.createdAt())
        );
    }

    @Test
    void save_persistsRowInDatabase_verifiedByFindByUserId() {
        WalletTransactionDTO saved = repository.save(
                2L, "WITHDRAWAL",
                new BigDecimal("200.00"),
                new BigDecimal("800.00"),
                new BigDecimal("600.00")
        );

        List<WalletTransactionDTO> rows = repository.findByUserId(2L);

        assertEquals(1, rows.size());
        WalletTransactionDTO persisted = rows.get(0);
        assertAll(
                () -> assertEquals(saved.transactionId(),       persisted.transactionId()),
                () -> assertEquals(2L,                          persisted.userId()),
                () -> assertEquals("WITHDRAWAL",                persisted.transactionType()),
                () -> assertEquals(new BigDecimal("200.00"),    persisted.amount()),
                () -> assertEquals(new BigDecimal("800.00"),    persisted.balanceBefore()),
                () -> assertEquals(new BigDecimal("600.00"),    persisted.balanceAfter()),
                () -> assertNotNull(persisted.createdAt())
        );
    }

    @Test
    void save_multipleTransactions_allPersistedWithDistinctIds() {
        WalletTransactionDTO deposit    = repository.save(3L, "DEPOSIT",    new BigDecimal("100.00"), new BigDecimal("0.00"),   new BigDecimal("100.00"));
        WalletTransactionDTO withdrawal = repository.save(3L, "WITHDRAWAL", new BigDecimal("40.00"),  new BigDecimal("100.00"), new BigDecimal("60.00"));

        assertAll(
                () -> assertNotNull(deposit.transactionId()),
                () -> assertNotNull(withdrawal.transactionId()),
                () -> assertTrue(deposit.transactionId() != withdrawal.transactionId())
        );

        List<WalletTransactionDTO> rows = repository.findByUserId(3L);
        assertEquals(2, rows.size());
    }

    // ── findByUserId ─────────────────────────────────────────────────────────────

    @Test
    void findByUserId_returnsEmptyList_whenNoTransactionsExistForUser() {
        assertTrue(repository.findByUserId(99L).isEmpty());
    }

    @Test
    void findByUserId_returnsOnlyTransactions_forTheRequestedUser() {
        repository.save(1L, "DEPOSIT",    new BigDecimal("100.00"), new BigDecimal("0.00"),   new BigDecimal("100.00"));
        repository.save(1L, "WITHDRAWAL", new BigDecimal("30.00"),  new BigDecimal("100.00"), new BigDecimal("70.00"));
        repository.save(2L, "DEPOSIT",    new BigDecimal("500.00"), new BigDecimal("0.00"),   new BigDecimal("500.00"));

        List<WalletTransactionDTO> user1 = repository.findByUserId(1L);
        List<WalletTransactionDTO> user2 = repository.findByUserId(2L);

        assertAll(
                () -> assertEquals(2, user1.size()),
                () -> assertTrue(user1.stream().allMatch(t -> t.userId() == 1L)),
                () -> assertEquals(1, user2.size()),
                () -> assertEquals("DEPOSIT", user2.get(0).transactionType())
        );
    }

    @Test
    void findByUserId_orderedByCreatedAtDescThenTransactionIdDesc() {
        LocalDateTime earlier = LocalDateTime.of(2026, 1, 1, 10, 0, 0);
        LocalDateTime later   = LocalDateTime.of(2026, 1, 2, 10, 0, 0);

        // Insert directly so we control created_at timestamps precisely
        insertTransaction(1L, 10L, "FIRST",  "50.00", "0.00",   "50.00",  earlier);
        insertTransaction(2L, 10L, "SECOND", "25.00", "50.00",  "75.00",  later);
        insertTransaction(3L, 10L, "THIRD",  "10.00", "75.00",  "85.00",  later);   // same timestamp, higher id → comes first

        List<WalletTransactionDTO> rows = repository.findByUserId(10L);

        assertEquals(3, rows.size());
        // ORDER BY created_at DESC → later rows come first;
        // tie-broken by transaction_id DESC → id 3 before id 2
        assertAll(
                () -> assertEquals("THIRD",  rows.get(0).transactionType()),
                () -> assertEquals("SECOND", rows.get(1).transactionType()),
                () -> assertEquals("FIRST",  rows.get(2).transactionType())
        );
    }

    // ── mapRow null createdAt branch ─────────────────────────────────────────────

    @Test
    void findByUserId_mapsNullCreatedAt_toNull() {
        // Insert a row with NULL created_at to exercise the null branch in mapRow
        jdbcTemplate.update(
                "INSERT INTO wallet_transactions (transaction_id, user_id, transaction_type, amount, balance_before, balance_after, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)",
                100L, 5L, "DEPOSIT",
                new BigDecimal("10.00"), new BigDecimal("0.00"), new BigDecimal("10.00"),
                null
        );

        List<WalletTransactionDTO> rows = repository.findByUserId(5L);

        assertEquals(1, rows.size());
        assertNull(rows.get(0).createdAt());
    }

    // ── Private Helper ────────────────────────────────────────────────────────────

    private void insertTransaction(long transactionId, long userId, String type,
                                   String amount, String balanceBefore, String balanceAfter,
                                   LocalDateTime createdAt) {
        jdbcTemplate.update(
                "INSERT INTO wallet_transactions (transaction_id, user_id, transaction_type, amount, balance_before, balance_after, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)",
                transactionId, userId, type,
                new BigDecimal(amount),
                new BigDecimal(balanceBefore),
                new BigDecimal(balanceAfter),
                Timestamp.valueOf(createdAt)
        );
    }
}
