package com.example.repository;

import com.example.model.AssetType;
import com.example.model.InvestmentGoal;
import com.example.model.InvestmentHorizon;
import com.example.model.Portfolio;
import com.example.model.PortfolioItem;
import com.example.model.RiskLevel;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertAll;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

@JdbcTest
@Import({PortfolioRepository.class, PortfolioItemRepository.class})
@TestPropertySource(properties = "spring.sql.init.mode=never")
class PortfolioRepositoryTest {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private PortfolioRepository repository;

    // ── Schema & Seed Helpers ────────────────────────────────────────────────────

    @BeforeEach
    void setUpSchema() {
        jdbcTemplate.execute("DROP ALL OBJECTS");
        jdbcTemplate.execute("""
                CREATE TABLE users (
                    user_id BIGINT PRIMARY KEY,
                    username VARCHAR(255) NOT NULL,
                    wallet_balance DECIMAL(19, 2) NOT NULL
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE portfolios (
                    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id    BIGINT NOT NULL,
                    portfolio_number BIGINT NOT NULL,
                    name       VARCHAR(255) NOT NULL,
                    description VARCHAR(1000),
                    currency   VARCHAR(10),
                    risk_level  VARCHAR(50),
                    investment_goal VARCHAR(50),
                    target_value DECIMAL(19, 4),
                    investment_horizon VARCHAR(50),
                    created_at TIMESTAMP NOT NULL,
                    updated_at TIMESTAMP,
                    FOREIGN KEY (user_id) REFERENCES users(user_id)
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE portfolio_items (
                    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    portfolio_id   BIGINT NOT NULL,
                    asset_type     VARCHAR(50) NOT NULL,
                    symbol         VARCHAR(255) NOT NULL,
                    name           VARCHAR(255) NOT NULL,
                    quantity       DECIMAL(19, 4) NOT NULL,
                    purchase_price DECIMAL(19, 2) NOT NULL,
                    current_price  DECIMAL(19, 2),
                    purchase_date  TIMESTAMP NOT NULL,
                    created_at     TIMESTAMP,
                    updated_at     TIMESTAMP,
                    notes          VARCHAR(1000),
                    FOREIGN KEY (portfolio_id) REFERENCES portfolios(id)
                )
                """);

        insertUser(1L, "alice", "5000.00");
        insertUser(2L, "bob",   "2000.00");
    }

    // ── findAll ──────────────────────────────────────────────────────────────────

    @Test
    void findAll_returnsEmptyList_whenTableIsEmpty() {
        assertTrue(repository.findAll().isEmpty());
    }

    @Test
    void findAll_returnsAllPortfolios_withItemsLoaded() {
        insertPortfolio(10L, 1L, 1L, "Growth", null, "USD",
                RiskLevel.AGGRESSIVE, InvestmentGoal.GROWTH, new BigDecimal("100000.0000"),
                InvestmentHorizon.LONG_TERM,
                LocalDateTime.of(2026, 1, 1, 0, 0),
                LocalDateTime.of(2026, 1, 2, 0, 0));
        insertPortfolio(20L, 2L, 1L, "Income", "Safe income", "EUR",
                RiskLevel.CONSERVATIVE, InvestmentGoal.INCOME, null,
                InvestmentHorizon.SHORT_TERM,
                LocalDateTime.of(2026, 2, 1, 0, 0),
                LocalDateTime.of(2026, 2, 2, 0, 0));
        insertPortfolioItem(10L, AssetType.STOCK, "AAPL", "Apple",
                "1.0000", "150.00", "170.00",
                LocalDateTime.of(2026, 1, 10, 9, 0));

        List<Portfolio> all = repository.findAll();

        assertEquals(2, all.size());
        Portfolio growth = all.stream().filter(p -> p.getId() == 10L).findFirst().orElseThrow();
        assertAll(
                () -> assertEquals(1L, growth.getUserId()),
                () -> assertEquals("Growth", growth.getName()),
                () -> assertEquals(RiskLevel.AGGRESSIVE, growth.getRiskLevel()),
                () -> assertEquals(InvestmentGoal.GROWTH, growth.getInvestmentGoal()),
                () -> assertEquals(InvestmentHorizon.LONG_TERM, growth.getInvestmentHorizon()),
                () -> assertEquals(new BigDecimal("100000.0000"), growth.getTargetValue()),
                () -> assertEquals("USD", growth.getCurrency()),
                () -> assertEquals(1, growth.getItems().size()),
                () -> assertEquals("AAPL", growth.getItems().get(0).getSymbol())
        );
    }

    // ── findByUserId ─────────────────────────────────────────────────────────────

    @Test
    void findByUserId_returnsPortfoliosOrderedByPortfolioNumber() {
        insertPortfolio(10L, 1L, 2L, "Second",  null, "USD", null, null, null, null,
                LocalDateTime.of(2026, 1, 1, 0, 0), LocalDateTime.of(2026, 1, 1, 0, 0));
        insertPortfolio(20L, 1L, 1L, "First",   null, "USD", null, null, null, null,
                LocalDateTime.of(2026, 1, 1, 0, 0), LocalDateTime.of(2026, 1, 1, 0, 0));
        insertPortfolio(30L, 2L, 1L, "OtherUser", null, "USD", null, null, null, null,
                LocalDateTime.of(2026, 1, 1, 0, 0), LocalDateTime.of(2026, 1, 1, 0, 0));

        List<Portfolio> result = repository.findByUserId(1L);

        assertEquals(2, result.size());
        assertEquals("First",  result.get(0).getName());
        assertEquals("Second", result.get(1).getName());
    }

    @Test
    void findByUserId_returnsEmptyList_forUnknownUser() {
        assertTrue(repository.findByUserId(999L).isEmpty());
    }

    // ── findByUserIdAndPortfolioNumber ───────────────────────────────────────────

    @Test
    void findByUserIdAndPortfolioNumber_presentAndMissing() {
        insertPortfolio(10L, 1L, 3L, "Third", null, "USD", null, null, null, null,
                LocalDateTime.of(2026, 1, 1, 0, 0), LocalDateTime.of(2026, 1, 1, 0, 0));

        Optional<Portfolio> found   = repository.findByUserIdAndPortfolioNumber(1L, 3L);
        Optional<Portfolio> missing = repository.findByUserIdAndPortfolioNumber(1L, 99L);

        assertAll(
                () -> assertTrue(found.isPresent()),
                () -> assertEquals("Third", found.orElseThrow().getName()),
                () -> assertTrue(missing.isEmpty())
        );
    }

    // ── findById ─────────────────────────────────────────────────────────────────

    @Test
    void findById_presentAndMissing() {
        insertPortfolio(10L, 1L, 1L, "Alpha", "desc", "GBP",
                RiskLevel.MODERATE, InvestmentGoal.BALANCED, new BigDecimal("50000.0000"),
                InvestmentHorizon.MEDIUM_TERM,
                LocalDateTime.of(2026, 3, 1, 8, 0),
                LocalDateTime.of(2026, 3, 2, 8, 0));

        Optional<Portfolio> found   = repository.findById(10L);
        Optional<Portfolio> missing = repository.findById(999L);

        assertAll(
                () -> assertTrue(found.isPresent()),
                () -> assertEquals("Alpha",                     found.orElseThrow().getName()),
                () -> assertEquals("desc",                      found.orElseThrow().getDescription()),
                () -> assertEquals("GBP",                       found.orElseThrow().getCurrency()),
                () -> assertEquals(RiskLevel.MODERATE,          found.orElseThrow().getRiskLevel()),
                () -> assertEquals(InvestmentGoal.BALANCED,     found.orElseThrow().getInvestmentGoal()),
                () -> assertEquals(InvestmentHorizon.MEDIUM_TERM, found.orElseThrow().getInvestmentHorizon()),
                () -> assertEquals(new BigDecimal("50000.0000"), found.orElseThrow().getTargetValue()),
                () -> assertNotNull(found.orElseThrow().getCreatedAt()),
                () -> assertNotNull(found.orElseThrow().getUpdatedAt()),
                () -> assertTrue(missing.isEmpty())
        );
    }

    @Test
    void findById_mapsNullUpdatedAt_andNullEnums() {
        // Insert directly so updated_at is NULL and all enum columns are NULL
        jdbcTemplate.update(
                "INSERT INTO portfolios (id, user_id, portfolio_number, name, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)",
                55L, 1L, 1L, "NullEnums",
                Timestamp.valueOf(LocalDateTime.of(2026, 5, 1, 0, 0)),
                null);

        Portfolio p = repository.findById(55L).orElseThrow();

        assertAll(
                () -> assertNull(p.getUpdatedAt()),
                () -> assertNull(p.getRiskLevel()),
                () -> assertNull(p.getInvestmentGoal()),
                () -> assertNull(p.getInvestmentHorizon()),
                () -> assertNull(p.getDescription()),
                () -> assertNull(p.getTargetValue())
        );
    }

    // ── findByName ───────────────────────────────────────────────────────────────

    @Test
    void findByName_presentAndMissing() {
        insertPortfolio(10L, 1L, 1L, "MyPortfolio", null, "USD", null, null, null, null,
                LocalDateTime.of(2026, 1, 1, 0, 0), LocalDateTime.of(2026, 1, 1, 0, 0));

        Optional<Portfolio> found   = repository.findByName("MyPortfolio");
        Optional<Portfolio> missing = repository.findByName("Ghost");

        assertAll(
                () -> assertTrue(found.isPresent()),
                () -> assertEquals(10L, found.orElseThrow().getId()),
                () -> assertTrue(missing.isEmpty())
        );
    }

    // ── existsById ───────────────────────────────────────────────────────────────

    @Test
    void existsById_trueAndFalse() {
        insertPortfolio(10L, 1L, 1L, "Exists", null, "USD", null, null, null, null,
                LocalDateTime.of(2026, 1, 1, 0, 0), LocalDateTime.of(2026, 1, 1, 0, 0));

        assertTrue(repository.existsById(10L));
        assertFalse(repository.existsById(999L));
    }

    // ── existsByName ─────────────────────────────────────────────────────────────

    @Test
    void existsByName_trueAndFalse() {
        insertPortfolio(10L, 1L, 1L, "Known", null, "USD", null, null, null, null,
                LocalDateTime.of(2026, 1, 1, 0, 0), LocalDateTime.of(2026, 1, 1, 0, 0));

        assertTrue(repository.existsByName("Known"));
        assertFalse(repository.existsByName("Unknown"));
    }

    // ── getNextPortfolioNumberByUserId ───────────────────────────────────────────

    @Test
    void getNextPortfolioNumber_returnsOne_whenUserHasNoPortfolios() {
        assertEquals(1L, repository.getNextPortfolioNumberByUserId(1L));
    }

    @Test
    void getNextPortfolioNumber_returnsMaxPlusOne_whenUserHasPortfolios() {
        insertPortfolio(10L, 1L, 1L, "First",  null, "USD", null, null, null, null,
                LocalDateTime.of(2026, 1, 1, 0, 0), LocalDateTime.of(2026, 1, 1, 0, 0));
        insertPortfolio(20L, 1L, 3L, "Third",  null, "USD", null, null, null, null,
                LocalDateTime.of(2026, 1, 1, 0, 0), LocalDateTime.of(2026, 1, 1, 0, 0));

        assertEquals(4L, repository.getNextPortfolioNumberByUserId(1L));
    }

    // ── save – insert ────────────────────────────────────────────────────────────

    @Test
    void save_insertsNewPortfolio_setsGeneratedIdAndTimestamps() {
        Portfolio p = buildPortfolio(null, 1L, 1L, "NewPort", null, "USD",
                null, null, null, null);

        Portfolio saved = repository.save(p);

        assertAll(
                () -> assertNotNull(saved.getId()),
                () -> assertNotNull(saved.getCreatedAt()),
                () -> assertNotNull(saved.getUpdatedAt()),
                () -> assertEquals("NewPort", saved.getName())
        );

        Portfolio persisted = repository.findById(saved.getId()).orElseThrow();
        assertAll(
                () -> assertEquals(1L,       persisted.getUserId()),
                () -> assertEquals("NewPort", persisted.getName()),
                () -> assertNull(persisted.getRiskLevel()),
                () -> assertNull(persisted.getInvestmentGoal()),
                () -> assertNull(persisted.getInvestmentHorizon())
        );
    }

    @Test
    void save_insertsPortfolioWithAllEnums_persistsEnumValuesCorrectly() {
        Portfolio p = buildPortfolio(null, 1L, 2L, "FullPort", "Rich desc", "JPY",
                RiskLevel.SPECULATIVE, InvestmentGoal.SPECULATION,
                new BigDecimal("999999.9999"), InvestmentHorizon.SHORT_TERM);

        Portfolio saved = repository.save(p);
        Portfolio persisted = repository.findById(saved.getId()).orElseThrow();

        assertAll(
                () -> assertEquals(RiskLevel.SPECULATIVE,       persisted.getRiskLevel()),
                () -> assertEquals(InvestmentGoal.SPECULATION,  persisted.getInvestmentGoal()),
                () -> assertEquals(InvestmentHorizon.SHORT_TERM, persisted.getInvestmentHorizon()),
                () -> assertEquals("Rich desc",                 persisted.getDescription()),
                () -> assertEquals("JPY",                       persisted.getCurrency()),
                () -> assertEquals(new BigDecimal("999999.9999"), persisted.getTargetValue())
        );
    }

    // ── save – update ────────────────────────────────────────────────────────────

    @Test
    void save_updatesExistingPortfolio_refreshesUpdatedAtAndPersistsAllChanges() {
        LocalDateTime oldUpdatedAt = LocalDateTime.of(2026, 1, 1, 0, 0);
        insertPortfolio(10L, 1L, 1L, "Old", "old desc", "USD",
                RiskLevel.CONSERVATIVE, InvestmentGoal.INCOME,
                new BigDecimal("10000.0000"), InvestmentHorizon.SHORT_TERM,
                LocalDateTime.of(2026, 1, 1, 0, 0), oldUpdatedAt);

        Portfolio existing = repository.findById(10L).orElseThrow();
        existing.setName("Updated");
        existing.setDescription("new desc");
        existing.setCurrency("EUR");
        existing.setRiskLevel(RiskLevel.AGGRESSIVE);
        existing.setInvestmentGoal(InvestmentGoal.GROWTH);
        existing.setTargetValue(new BigDecimal("99999.0000"));
        existing.setInvestmentHorizon(InvestmentHorizon.LONG_TERM);

        Portfolio updated = repository.save(existing);

        assertNotNull(updated.getUpdatedAt());
        assertTrue(updated.getUpdatedAt().isAfter(oldUpdatedAt));

        Portfolio persisted = repository.findById(10L).orElseThrow();
        assertAll(
                () -> assertEquals("Updated",             persisted.getName()),
                () -> assertEquals("new desc",            persisted.getDescription()),
                () -> assertEquals("EUR",                 persisted.getCurrency()),
                () -> assertEquals(RiskLevel.AGGRESSIVE,  persisted.getRiskLevel()),
                () -> assertEquals(InvestmentGoal.GROWTH, persisted.getInvestmentGoal()),
                () -> assertEquals(InvestmentHorizon.LONG_TERM, persisted.getInvestmentHorizon()),
                () -> assertEquals(new BigDecimal("99999.0000"), persisted.getTargetValue())
        );
    }

    @Test
    void save_updateClearsNullableEnumsToNull() {
        insertPortfolio(10L, 1L, 1L, "HasEnums", null, "USD",
                RiskLevel.MODERATE, InvestmentGoal.BALANCED, new BigDecimal("5000.0000"),
                InvestmentHorizon.MEDIUM_TERM,
                LocalDateTime.of(2026, 1, 1, 0, 0),
                LocalDateTime.of(2026, 1, 1, 0, 0));

        Portfolio existing = repository.findById(10L).orElseThrow();
        existing.setRiskLevel(null);
        existing.setInvestmentGoal(null);
        existing.setInvestmentHorizon(null);
        existing.setTargetValue(null);
        repository.save(existing);

        Portfolio persisted = repository.findById(10L).orElseThrow();
        assertAll(
                () -> assertNull(persisted.getRiskLevel()),
                () -> assertNull(persisted.getInvestmentGoal()),
                () -> assertNull(persisted.getInvestmentHorizon()),
                () -> assertNull(persisted.getTargetValue())
        );
    }

    // ── deleteById ───────────────────────────────────────────────────────────────

    @Test
    void deleteById_removesOnlyTargetPortfolio_leavesOthersIntact() {
        insertPortfolio(10L, 1L, 1L, "ToDelete", null, "USD", null, null, null, null,
                LocalDateTime.of(2026, 1, 1, 0, 0), LocalDateTime.of(2026, 1, 1, 0, 0));
        insertPortfolio(20L, 1L, 2L, "ToKeep", null, "USD", null, null, null, null,
                LocalDateTime.of(2026, 1, 1, 0, 0), LocalDateTime.of(2026, 1, 1, 0, 0));

        repository.deleteById(10L);

        assertAll(
                () -> assertTrue(repository.findById(10L).isEmpty()),
                () -> assertTrue(repository.findById(20L).isPresent()),
                () -> assertEquals(1, repository.findAll().size())
        );
    }

    // ── loadWithItems (via findById) ──────────────────────────────────────────────

    @Test
    void findById_loadsAssociatedPortfolioItems() {
        insertPortfolio(10L, 1L, 1L, "WithItems", null, "USD", null, null, null, null,
                LocalDateTime.of(2026, 1, 1, 0, 0), LocalDateTime.of(2026, 1, 1, 0, 0));
        insertPortfolioItem(10L, AssetType.ETF, "VTI",  "Vanguard",  "5.0000", "200.00", "210.00", LocalDateTime.of(2026, 2, 1, 9, 0));
        insertPortfolioItem(10L, AssetType.BOND, "TLT", "Treasury", "3.0000",  "95.00",  "92.00", LocalDateTime.of(2026, 2, 2, 9, 0));

        Portfolio p = repository.findById(10L).orElseThrow();

        assertEquals(2, p.getItems().size());
        List<String> symbols = p.getItems().stream().map(PortfolioItem::getSymbol).sorted().toList();
        assertEquals(List.of("TLT", "VTI"), symbols);
    }

    @Test
    void findByUserId_loadsItemsForEachPortfolio() {
        insertPortfolio(10L, 1L, 1L, "P1", null, "USD", null, null, null, null,
                LocalDateTime.of(2026, 1, 1, 0, 0), LocalDateTime.of(2026, 1, 1, 0, 0));
        insertPortfolio(20L, 1L, 2L, "P2", null, "USD", null, null, null, null,
                LocalDateTime.of(2026, 1, 1, 0, 0), LocalDateTime.of(2026, 1, 1, 0, 0));
        insertPortfolioItem(10L, AssetType.STOCK, "AAPL", "Apple", "1.0000", "150.00", "170.00", LocalDateTime.of(2026, 2, 1, 9, 0));
        insertPortfolioItem(20L, AssetType.STOCK, "GOOG", "Google", "2.0000", "100.00", "110.00", LocalDateTime.of(2026, 2, 1, 9, 0));

        List<Portfolio> portfolios = repository.findByUserId(1L);

        Portfolio p1 = portfolios.stream().filter(p -> p.getName().equals("P1")).findFirst().orElseThrow();
        Portfolio p2 = portfolios.stream().filter(p -> p.getName().equals("P2")).findFirst().orElseThrow();
        assertAll(
                () -> assertEquals(1, p1.getItems().size()),
                () -> assertEquals("AAPL", p1.getItems().get(0).getSymbol()),
                () -> assertEquals(1, p2.getItems().size()),
                () -> assertEquals("GOOG", p2.getItems().get(0).getSymbol())
        );
    }

    // ── Private Helpers ──────────────────────────────────────────────────────────

    private void insertUser(Long userId, String username, String walletBalance) {
        jdbcTemplate.update(
                "INSERT INTO users (user_id, username, wallet_balance) VALUES (?, ?, ?)",
                userId, username, new BigDecimal(walletBalance));
    }

    private void insertPortfolio(Long id, Long userId, Long portfolioNumber, String name,
                                  String description, String currency,
                                  RiskLevel riskLevel, InvestmentGoal investmentGoal,
                                  BigDecimal targetValue, InvestmentHorizon investmentHorizon,
                                  LocalDateTime createdAt, LocalDateTime updatedAt) {
        jdbcTemplate.update(
                "INSERT INTO portfolios (id, user_id, portfolio_number, name, description, currency, " +
                "risk_level, investment_goal, target_value, investment_horizon, created_at, updated_at) " +
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                id, userId, portfolioNumber, name, description, currency,
                riskLevel != null ? riskLevel.name() : null,
                investmentGoal != null ? investmentGoal.name() : null,
                targetValue,
                investmentHorizon != null ? investmentHorizon.name() : null,
                Timestamp.valueOf(createdAt),
                updatedAt != null ? Timestamp.valueOf(updatedAt) : null);
    }

    private void insertPortfolioItem(Long portfolioId, AssetType assetType,
                                      String symbol, String name,
                                      String quantity, String purchasePrice,
                                      String currentPrice, LocalDateTime purchaseDate) {
        jdbcTemplate.update(
                "INSERT INTO portfolio_items (portfolio_id, asset_type, symbol, name, quantity, " +
                "purchase_price, current_price, purchase_date, created_at, updated_at) " +
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                portfolioId, assetType.name(), symbol, name,
                new BigDecimal(quantity), new BigDecimal(purchasePrice),
                new BigDecimal(currentPrice),
                Timestamp.valueOf(purchaseDate),
                Timestamp.valueOf(purchaseDate),
                Timestamp.valueOf(purchaseDate));
    }

    private Portfolio buildPortfolio(Long id, Long userId, Long portfolioNumber, String name,
                                      String description, String currency,
                                      RiskLevel riskLevel, InvestmentGoal investmentGoal,
                                      BigDecimal targetValue, InvestmentHorizon investmentHorizon) {
        Portfolio p = new Portfolio();
        p.setId(id);
        p.setUserId(userId);
        p.setPortfolioNumber(portfolioNumber);
        p.setName(name);
        p.setDescription(description);
        p.setCurrency(currency);
        p.setRiskLevel(riskLevel);
        p.setInvestmentGoal(investmentGoal);
        p.setTargetValue(targetValue);
        p.setInvestmentHorizon(investmentHorizon);
        return p;
    }
}
