package com.example.repository;

import com.example.model.AssetType;
import com.example.model.Portfolio;
import com.example.model.PortfolioItem;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertAll;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

@JdbcTest
@Import(PortfolioItemRepository.class)
@TestPropertySource(properties = "spring.sql.init.mode=never")
class PortfolioItemRepositoryTest {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private PortfolioItemRepository repository;

    @BeforeEach
    void setUpSchema() {
        jdbcTemplate.execute("DROP ALL OBJECTS");
        jdbcTemplate.execute("""
                CREATE TABLE users (
                    user_id BIGINT PRIMARY KEY,
                    username VARCHAR(255) NOT NULL,
                    wallet_balance DECIMAL(19, 2) NOT NULL
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE portfolios (
                    id BIGINT PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    portfolio_number BIGINT NOT NULL,
                    name VARCHAR(255) NOT NULL,
                    description VARCHAR(1000),
                    currency VARCHAR(10),
                    risk_level VARCHAR(50),
                    investment_goal VARCHAR(50),
                    target_value DECIMAL(19, 4),
                    investment_horizon VARCHAR(50),
                    created_at TIMESTAMP,
                    updated_at TIMESTAMP,
                    FOREIGN KEY (user_id) REFERENCES users(user_id)
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE portfolio_items (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    portfolio_id BIGINT NOT NULL,
                    asset_type VARCHAR(50) NOT NULL,
                    symbol VARCHAR(255) NOT NULL,
                    name VARCHAR(255) NOT NULL,
                    quantity DECIMAL(19, 4) NOT NULL,
                    purchase_price DECIMAL(19, 2) NOT NULL,
                    current_price DECIMAL(19, 2),
                    purchase_date TIMESTAMP NOT NULL,
                    created_at TIMESTAMP,
                    updated_at TIMESTAMP,
                    notes VARCHAR(1000),
                    FOREIGN KEY (portfolio_id) REFERENCES portfolios(id)
                )
                """);

        insertUser(1L, "alpha", "1000.00");
        insertUser(2L, "beta", "2000.00");
        insertPortfolio(10L, 1L, "Growth");
        insertPortfolio(20L, 2L, "Income");
    }

    @Test
    void findByPortfolioId_mapsRowsIncludingNullableFields() {
        LocalDateTime purchaseDate = LocalDateTime.of(2026, 8, 4, 9, 30);
        LocalDateTime createdAt = LocalDateTime.of(2026, 8, 4, 10, 0);
        insertPortfolioItem(1L, 10L, AssetType.STOCK, "AAPL", "Apple", "2.5000", "150.00", "175.50", purchaseDate, createdAt, null, "core");
        insertPortfolioItem(2L, 10L, AssetType.CASH, "USD", "US Dollar", "50.0000", "1.00", null, purchaseDate.plusDays(1), null, null, null);

        List<PortfolioItem> items = repository.findByPortfolioId(10L);

        assertEquals(2, items.size());
        PortfolioItem first = items.get(0);
        PortfolioItem second = items.get(1);
        assertAll(
                () -> assertEquals(1L, first.getId()),
                () -> assertEquals(10L, first.getPortfolio().getId()),
                () -> assertEquals(AssetType.STOCK, first.getAssetType()),
                () -> assertEquals("AAPL", first.getSymbol()),
                () -> assertEquals(new BigDecimal("2.5000"), first.getQuantity()),
                () -> assertEquals(new BigDecimal("150.00"), first.getPurchasePrice()),
                () -> assertEquals(new BigDecimal("175.50"), first.getCurrentPrice()),
                () -> assertEquals(purchaseDate, first.getPurchaseDate()),
                () -> assertEquals(createdAt, first.getCreatedAt()),
                () -> assertNull(first.getUpdatedAt()),
                () -> assertEquals("core", first.getNotes()),
                () -> assertNull(second.getCurrentPrice()),
                () -> assertNull(second.getCreatedAt()),
                () -> assertNull(second.getUpdatedAt()),
                () -> assertNull(second.getNotes())
        );
    }

    @Test
    void findByPortfolioIdAndAssetType_returnsOnlyMatchingAssetType() {
        LocalDateTime purchaseDate = LocalDateTime.of(2026, 8, 4, 9, 30);
        insertPortfolioItem(1L, 10L, AssetType.STOCK, "AAPL", "Apple", "1.0000", "150.00", "175.50", purchaseDate, null, null, null);
        insertPortfolioItem(2L, 10L, AssetType.ETF, "QQQ", "QQQ", "3.0000", "400.00", "510.10", purchaseDate, null, null, null);

        List<PortfolioItem> items = repository.findByPortfolioIdAndAssetType(10L, AssetType.ETF);

        assertEquals(1, items.size());
        assertEquals("QQQ", items.get(0).getSymbol());
        assertEquals(AssetType.ETF, items.get(0).getAssetType());
    }

    @Test
    void findByPortfolioIdAndSymbol_returnsOptionalForMatchAndEmptyWhenMissing() {
        LocalDateTime purchaseDate = LocalDateTime.of(2026, 8, 4, 9, 30);
        insertPortfolioItem(1L, 10L, AssetType.STOCK, "MSFT", "Microsoft", "4.0000", "250.00", "380.00", purchaseDate, null, null, null);

        Optional<PortfolioItem> found = repository.findByPortfolioIdAndSymbol(10L, "MSFT");
        Optional<PortfolioItem> missing = repository.findByPortfolioIdAndSymbol(10L, "NVDA");

        assertTrue(found.isPresent());
        assertEquals("Microsoft", found.orElseThrow().getName());
        assertTrue(missing.isEmpty());
    }

    @Test
    void findBySymbol_returnsMatchesAcrossPortfolios() {
        LocalDateTime purchaseDate = LocalDateTime.of(2026, 8, 4, 9, 30);
        insertPortfolioItem(1L, 10L, AssetType.STOCK, "KO", "Coca-Cola", "2.0000", "50.00", "60.00", purchaseDate, null, null, null);
        insertPortfolioItem(2L, 20L, AssetType.STOCK, "KO", "Coca-Cola", "3.0000", "55.00", "60.00", purchaseDate, null, null, null);
        insertPortfolioItem(3L, 20L, AssetType.STOCK, "PEP", "Pepsi", "1.0000", "150.00", "170.00", purchaseDate, null, null, null);

        List<PortfolioItem> items = repository.findBySymbol("KO");

        assertEquals(2, items.size());
        assertEquals(List.of(10L, 20L), items.stream().map(item -> item.getPortfolio().getId()).sorted().toList());
    }

    @Test
    void findByIdAndExistsById_handlePresentAndMissingRows() {
        LocalDateTime purchaseDate = LocalDateTime.of(2026, 8, 4, 9, 30);
        insertPortfolioItem(1L, 10L, AssetType.STOCK, "NVDA", "NVIDIA", "1.0000", "100.00", "120.00", purchaseDate, null, null, null);

        Optional<PortfolioItem> found = repository.findById(1L);
        Optional<PortfolioItem> missing = repository.findById(99L);

        assertAll(
                () -> assertTrue(found.isPresent()),
                () -> assertEquals("NVDA", found.orElseThrow().getSymbol()),
                () -> assertTrue(missing.isEmpty()),
                () -> assertTrue(repository.existsById(1L)),
                () -> assertFalse(repository.existsById(99L))
        );
    }

    @Test
    void save_insertsNewItem_setsGeneratedIdAndDefaultTimestamps() {
        PortfolioItem item = new PortfolioItem();
        item.setPortfolio(portfolioRef(10L));
        item.setAssetType(AssetType.STOCK);
        item.setSymbol("TSLA");
        item.setName("Tesla");
        item.setQuantity(new BigDecimal("2.2500"));
        item.setPurchasePrice(new BigDecimal("210.00"));
        item.setCurrentPrice(new BigDecimal("230.00"));
        item.setPurchaseDate(null);
        item.setNotes("inserted");

        PortfolioItem saved = repository.save(item);

        assertAll(
                () -> assertNotNull(saved.getId()),
                () -> assertNotNull(saved.getCreatedAt()),
                () -> assertNotNull(saved.getUpdatedAt()),
                () -> assertNotNull(saved.getPurchaseDate()),
                () -> assertEquals("TSLA", saved.getSymbol())
        );

        PortfolioItem persisted = repository.findById(saved.getId()).orElseThrow();
        assertAll(
                () -> assertEquals(new BigDecimal("2.2500"), persisted.getQuantity()),
                () -> assertEquals(new BigDecimal("210.00"), persisted.getPurchasePrice()),
                () -> assertEquals(new BigDecimal("230.00"), persisted.getCurrentPrice()),
                () -> assertEquals("inserted", persisted.getNotes())
        );
    }

    @Test
    void save_updatesExistingItem_andRefreshesUpdatedAt() {
        LocalDateTime purchaseDate = LocalDateTime.of(2026, 8, 4, 9, 30);
        LocalDateTime oldUpdatedAt = LocalDateTime.of(2026, 8, 4, 10, 0);
        insertPortfolioItem(1L, 10L, AssetType.STOCK, "AMD", "AMD", "5.0000", "120.00", "125.00", purchaseDate, purchaseDate, oldUpdatedAt, "before");

        PortfolioItem existing = repository.findById(1L).orElseThrow();
        existing.setAssetType(AssetType.ETF);
        existing.setSymbol("VTI");
        existing.setName("Vanguard Total Stock Market ETF");
        existing.setQuantity(new BigDecimal("7.5000"));
        existing.setPurchasePrice(new BigDecimal("130.00"));
        existing.setCurrentPrice(new BigDecimal("140.00"));
        existing.setPurchaseDate(purchaseDate.plusDays(2));
        existing.setNotes("updated");

        PortfolioItem updated = repository.save(existing);

        assertNotNull(updated.getUpdatedAt());
        assertTrue(updated.getUpdatedAt().isAfter(oldUpdatedAt));

        PortfolioItem persisted = repository.findById(1L).orElseThrow();
        assertAll(
                () -> assertEquals(AssetType.ETF, persisted.getAssetType()),
                () -> assertEquals("VTI", persisted.getSymbol()),
                () -> assertEquals("Vanguard Total Stock Market ETF", persisted.getName()),
                () -> assertEquals(new BigDecimal("7.5000"), persisted.getQuantity()),
                () -> assertEquals(new BigDecimal("130.00"), persisted.getPurchasePrice()),
                () -> assertEquals(new BigDecimal("140.00"), persisted.getCurrentPrice()),
                () -> assertEquals(purchaseDate.plusDays(2), persisted.getPurchaseDate()),
                () -> assertEquals("updated", persisted.getNotes())
        );
    }

    @Test
    void saveAll_persistsMixedExistingAndNewItems() {
        LocalDateTime purchaseDate = LocalDateTime.of(2026, 8, 4, 9, 30);
        insertPortfolioItem(100L, 10L, AssetType.STOCK, "AAPL", "Apple", "1.0000", "150.00", "175.00", purchaseDate, purchaseDate, purchaseDate, "existing");

        PortfolioItem existing = repository.findById(100L).orElseThrow();
        existing.setQuantity(new BigDecimal("4.0000"));
        existing.setNotes("existing-updated");

        PortfolioItem fresh = new PortfolioItem();
        fresh.setPortfolio(portfolioRef(20L));
        fresh.setAssetType(AssetType.BOND);
        fresh.setSymbol("TLT");
        fresh.setName("Treasury Bond ETF");
        fresh.setQuantity(new BigDecimal("8.0000"));
        fresh.setPurchasePrice(new BigDecimal("95.00"));
        fresh.setCurrentPrice(null);
        fresh.setPurchaseDate(purchaseDate.plusDays(1));
        fresh.setNotes("new-item");

        List<PortfolioItem> saved = repository.saveAll(List.of(existing, fresh));

        assertEquals(2, saved.size());
        assertNotNull(fresh.getId());
        assertEquals(new BigDecimal("4.0000"), repository.findById(100L).orElseThrow().getQuantity());
        assertEquals("new-item", repository.findById(fresh.getId()).orElseThrow().getNotes());
    }

    @Test
    void deleteById_removesSingleItem() {
        LocalDateTime purchaseDate = LocalDateTime.of(2026, 8, 4, 9, 30);
        insertPortfolioItem(1L, 10L, AssetType.STOCK, "AAPL", "Apple", "1.0000", "150.00", "175.00", purchaseDate, null, null, null);
        insertPortfolioItem(2L, 10L, AssetType.STOCK, "MSFT", "Microsoft", "1.0000", "250.00", "380.00", purchaseDate, null, null, null);

        repository.deleteById(1L);

        assertTrue(repository.findById(1L).isEmpty());
        assertEquals(List.of("MSFT"), repository.findByPortfolioId(10L).stream().map(PortfolioItem::getSymbol).toList());
    }

    @Test
    void deleteByPortfolioId_removesOnlyRowsForThatPortfolio() {
        LocalDateTime purchaseDate = LocalDateTime.of(2026, 8, 4, 9, 30);
        insertPortfolioItem(1L, 10L, AssetType.STOCK, "AAPL", "Apple", "1.0000", "150.00", "175.00", purchaseDate, null, null, null);
        insertPortfolioItem(2L, 10L, AssetType.STOCK, "MSFT", "Microsoft", "1.0000", "250.00", "380.00", purchaseDate, null, null, null);
        insertPortfolioItem(3L, 20L, AssetType.BOND, "TLT", "Bond ETF", "3.0000", "95.00", "90.00", purchaseDate, null, null, null);

        repository.deleteByPortfolioId(10L);

        assertTrue(repository.findByPortfolioId(10L).isEmpty());
        assertEquals(List.of("TLT"), repository.findByPortfolioId(20L).stream().map(PortfolioItem::getSymbol).toList());
    }

    private void insertUser(Long userId, String username, String walletBalance) {
        jdbcTemplate.update(
                "INSERT INTO users (user_id, username, wallet_balance) VALUES (?, ?, ?)",
                userId, username, new BigDecimal(walletBalance));
    }

    private void insertPortfolio(Long id, Long userId, String name) {
        jdbcTemplate.update(
                "INSERT INTO portfolios (id, user_id, portfolio_number, name, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)",
                id, userId, 1L, name,
                Timestamp.valueOf(LocalDateTime.of(2026, 8, 4, 8, 0)),
                Timestamp.valueOf(LocalDateTime.of(2026, 8, 4, 8, 30)));
    }

    private void insertPortfolioItem(Long id,
                                     Long portfolioId,
                                     AssetType assetType,
                                     String symbol,
                                     String name,
                                     String quantity,
                                     String purchasePrice,
                                     String currentPrice,
                                     LocalDateTime purchaseDate,
                                     LocalDateTime createdAt,
                                     LocalDateTime updatedAt,
                                     String notes) {
        jdbcTemplate.update(
                "INSERT INTO portfolio_items (id, portfolio_id, asset_type, symbol, name, quantity, purchase_price, current_price, purchase_date, created_at, updated_at, notes) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                id,
                portfolioId,
                assetType.name(),
                symbol,
                name,
                new BigDecimal(quantity),
                new BigDecimal(purchasePrice),
                currentPrice == null ? null : new BigDecimal(currentPrice),
                Timestamp.valueOf(purchaseDate),
                createdAt == null ? null : Timestamp.valueOf(createdAt),
                updatedAt == null ? null : Timestamp.valueOf(updatedAt),
                notes);
    }

    private Portfolio portfolioRef(Long id) {
        Portfolio portfolio = new Portfolio();
        portfolio.setId(id);
        return portfolio;
    }
}



