package com.example.repository;

import com.example.model.User;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;

import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertAll;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

@JdbcTest
@Import(UserRepository.class)
@TestPropertySource(properties = "spring.sql.init.mode=never")
class UserRepositoryTest {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private UserRepository repository;

    // ── Schema Setup ─────────────────────────────────────────────────────────────

    @BeforeEach
    void setUpSchema() {
        jdbcTemplate.execute("DROP ALL OBJECTS");
        // wallet_balance is nullable here so we can exercise the null→ZERO branch in mapRow
        jdbcTemplate.execute("""
                CREATE TABLE users (
                    user_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username       VARCHAR(255) NOT NULL,
                    wallet_balance DECIMAL(19, 2)
                )
                """);
    }

    // ── findAll ──────────────────────────────────────────────────────────────────

    @Test
    void findAll_returnsEmptyList_whenTableIsEmpty() {
        assertTrue(repository.findAll().isEmpty());
    }

    @Test
    void findAll_returnsAllUsers() {
        insertUser(1L, "alice", "1500.00");
        insertUser(2L, "bob",   "2500.00");

        List<User> users = repository.findAll();

        assertEquals(2, users.size());
        assertTrue(users.stream().anyMatch(u -> u.getUsername().equals("alice")));
        assertTrue(users.stream().anyMatch(u -> u.getUsername().equals("bob")));
    }

    // ── findById ─────────────────────────────────────────────────────────────────

    @Test
    void findById_returnsUser_whenPresent() {
        insertUser(10L, "charlie", "500.00");

        Optional<User> found = repository.findById(10L);

        assertAll(
                () -> assertTrue(found.isPresent()),
                () -> assertEquals(10L,                    found.orElseThrow().getUserId()),
                () -> assertEquals("charlie",              found.orElseThrow().getUsername()),
                () -> assertEquals(new BigDecimal("500.00"), found.orElseThrow().getWalletBalance())
        );
    }

    @Test
    void findById_returnsEmpty_whenMissing() {
        assertTrue(repository.findById(999L).isEmpty());
    }

    // ── mapRow null wallet_balance branch ────────────────────────────────────────

    @Test
    void findById_mapsNullWalletBalance_toBigDecimalZero() {
        // Insert with NULL wallet_balance to exercise the null→ZERO branch in mapRow
        jdbcTemplate.update(
                "INSERT INTO users (user_id, username, wallet_balance) VALUES (?, ?, ?)",
                5L, "nullbal", null);

        User user = repository.findById(5L).orElseThrow();

        assertEquals(BigDecimal.ZERO, user.getWalletBalance());
    }

    // ── findByUsername ───────────────────────────────────────────────────────────

    @Test
    void findByUsername_returnsUser_whenPresent() {
        insertUser(10L, "diana", "750.00");

        Optional<User> found = repository.findByUsername("diana");

        assertAll(
                () -> assertTrue(found.isPresent()),
                () -> assertEquals("diana", found.orElseThrow().getUsername())
        );
    }

    @Test
    void findByUsername_returnsEmpty_whenMissing() {
        assertTrue(repository.findByUsername("ghost").isEmpty());
    }

    // ── existsById ───────────────────────────────────────────────────────────────

    @Test
    void existsById_trueAndFalse() {
        insertUser(10L, "eve", "100.00");

        assertTrue(repository.existsById(10L));
        assertFalse(repository.existsById(999L));
    }

    // ── existsByUsername ─────────────────────────────────────────────────────────

    @Test
    void existsByUsername_trueAndFalse() {
        insertUser(10L, "frank", "200.00");

        assertTrue(repository.existsByUsername("frank"));
        assertFalse(repository.existsByUsername("unknown"));
    }

    // ── save – insert ────────────────────────────────────────────────────────────

    @Test
    void save_insertsNewUser_setsGeneratedId() {
        User user = new User();
        user.setUsername("grace");
        user.setWalletBalance(new BigDecimal("3000.00"));

        User saved = repository.save(user);

        assertAll(
                () -> assertNotNull(saved.getUserId()),
                () -> assertEquals("grace",                    saved.getUsername()),
                () -> assertEquals(new BigDecimal("3000.00"), saved.getWalletBalance())
        );

        User persisted = repository.findById(saved.getUserId()).orElseThrow();
        assertAll(
                () -> assertEquals("grace",                    persisted.getUsername()),
                () -> assertEquals(new BigDecimal("3000.00"), persisted.getWalletBalance())
        );
    }

    @Test
    void save_insertsNewUser_withNullWalletBalance_defaultsToZero() {
        User user = new User();
        user.setUsername("henry");
        user.setWalletBalance(null);

        User saved = repository.save(user);

        User persisted = repository.findById(saved.getUserId()).orElseThrow();
        // insert path substitutes null→ZERO before persisting (compare ignoring scale)
        assertEquals(0, BigDecimal.ZERO.compareTo(persisted.getWalletBalance()));
    }

    // ── save – update ────────────────────────────────────────────────────────────

    @Test
    void save_updatesExistingUser_persistsNewUsernameAndBalance() {
        insertUser(10L, "ivan", "100.00");

        User existing = repository.findById(10L).orElseThrow();
        existing.setUsername("ivan-renamed");
        existing.setWalletBalance(new BigDecimal("9999.99"));

        repository.save(existing);

        User persisted = repository.findById(10L).orElseThrow();
        assertAll(
                () -> assertEquals("ivan-renamed",             persisted.getUsername()),
                () -> assertEquals(new BigDecimal("9999.99"), persisted.getWalletBalance())
        );
    }

    @Test
    void save_updatesExistingUser_withNullWalletBalance_defaultsToZero() {
        insertUser(10L, "julia", "500.00");

        User existing = repository.findById(10L).orElseThrow();
        existing.setWalletBalance(null);
        repository.save(existing);

        User persisted = repository.findById(10L).orElseThrow();
        // update path substitutes null→ZERO (compare ignoring scale)
        assertEquals(0, BigDecimal.ZERO.compareTo(persisted.getWalletBalance()));
    }

    // ── getWalletBalance ─────────────────────────────────────────────────────────

    @Test
    void getWalletBalance_returnsBalance_forExistingUser() {
        insertUser(10L, "karen", "1234.56");

        Optional<BigDecimal> balance = repository.getWalletBalance(10L);

        assertAll(
                () -> assertTrue(balance.isPresent()),
                () -> assertEquals(new BigDecimal("1234.56"), balance.orElseThrow())
        );
    }

    @Test
    void getWalletBalance_returnsEmpty_forMissingUser() {
        assertTrue(repository.getWalletBalance(999L).isEmpty());
    }

    @Test
    void getWalletBalance_returnsZero_whenStoredBalanceIsNull() {
        jdbcTemplate.update(
                "INSERT INTO users (user_id, username, wallet_balance) VALUES (?, ?, ?)",
                7L, "nulluser", null);

        Optional<BigDecimal> balance = repository.getWalletBalance(7L);

        assertAll(
                () -> assertTrue(balance.isPresent()),
                () -> assertEquals(BigDecimal.ZERO, balance.orElseThrow())
        );
    }

    // ── addMoney ─────────────────────────────────────────────────────────────────

    @Test
    void addMoney_returnsTrue_andIncreasesBalance_forExistingUser() {
        insertUser(10L, "leo", "100.00");

        boolean result = repository.addMoney(10L, new BigDecimal("50.00"));

        assertTrue(result);
        assertEquals(new BigDecimal("150.00"),
                repository.getWalletBalance(10L).orElseThrow());
    }

    @Test
    void addMoney_returnsFalse_forNonExistentUser() {
        assertFalse(repository.addMoney(999L, new BigDecimal("50.00")));
    }

    // ── removeMoney ──────────────────────────────────────────────────────────────

    @Test
    void removeMoney_returnsTrue_andDecreasesBalance_whenFundsAreSufficient() {
        insertUser(10L, "mia", "500.00");

        boolean result = repository.removeMoney(10L, new BigDecimal("200.00"));

        assertTrue(result);
        assertEquals(new BigDecimal("300.00"),
                repository.getWalletBalance(10L).orElseThrow());
    }

    @Test
    void removeMoney_returnsTrue_whenAmountEqualsBalance() {
        insertUser(10L, "nina", "100.00");

        boolean result = repository.removeMoney(10L, new BigDecimal("100.00"));

        assertTrue(result);
        assertEquals(BigDecimal.ZERO,
                repository.getWalletBalance(10L).orElseThrow().stripTrailingZeros());
    }

    @Test
    void removeMoney_returnsFalse_whenBalanceIsInsufficient() {
        insertUser(10L, "oscar", "50.00");

        boolean result = repository.removeMoney(10L, new BigDecimal("100.00"));

        assertFalse(result);
        // balance must be unchanged
        assertEquals(new BigDecimal("50.00"),
                repository.getWalletBalance(10L).orElseThrow());
    }

    @Test
    void removeMoney_returnsFalse_forNonExistentUser() {
        assertFalse(repository.removeMoney(999L, new BigDecimal("10.00")));
    }

    // ── deleteById ───────────────────────────────────────────────────────────────

    @Test
    void deleteById_removesOnlyTargetUser_leavesOthersIntact() {
        insertUser(10L, "paul",  "100.00");
        insertUser(20L, "quinn", "200.00");

        repository.deleteById(10L);

        assertAll(
                () -> assertFalse(repository.existsById(10L)),
                () -> assertTrue(repository.existsById(20L)),
                () -> assertEquals(1, repository.findAll().size())
        );
    }

    // ── Private Helper ───────────────────────────────────────────────────────────

    private void insertUser(Long userId, String username, String walletBalance) {
        jdbcTemplate.update(
                "INSERT INTO users (user_id, username, wallet_balance) VALUES (?, ?, ?)",
                userId, username, new BigDecimal(walletBalance));
    }
}
